
name: GH Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:      
  pull_request:
permissions:
  contents: read
  pages: write
  id-token: write    
concurrency:
  group: "pages"
  cancel-in-progress: false  
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'npm'
      
      - name: Cache Eleventy Data
        uses: actions/cache@v4
        with:
          path: |
            .cache
            dist
          # This key changes whenever your notes or packages change
          key: ${{ runner.os }}-eleventy-${{ hashFiles('**/package-lock.json') }}-${{ github.run_id }}
          # This allows it to "restore" from the most recent successful build
          restore-keys: |
            ${{ runner.os }}-eleventy-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-eleventy-   
      - run: npm install
      
      # This runs your theme setup, sass build, AND eleventy with the prefix, portable if you change
      # site name
      #- run: npm run build -- --pathprefix=${{ github.event.repository.name }}
      - run: npm run build -- --pathprefix=/digitalgarden/
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


